### ISSUE TITLE
Pass in multiple sets of orbital parameters into kepler.py

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#16]
Especially for OFTI, it'd be great to pass in arrays of orbital parameters into `kepler.calc_orbit`. 

Basically the `epochs` argument can be of length M and the `sma`, `ecc`, etc arguments can be of length N, and the return values (e.g., `raoff`) should be of dimension NxM.

This will requiring formatting the code to angle scalars/1-D vectors at the same time, as well as 1-D/2-D vectors at the same time. It would be great to avoid code duplication. I _think_ this is possible.

**Comment by henry-ngo** [comment]
Okay so the branch vectorize_kepler has some basic functionality for passing in arrays of orbital parameters now! From my commit notes:

For calculations with 2-D arrays, currently looping through the "epochs" dimension (number of dates) because 1) it's likely to be smaller and 2) it prevents a lot of issues where sometimes we need to treat a keplerian element as a vector vs. a scalar.

The exception is the calculation of the eccentric anomaly, which is still done with a single value of eccentricity. Further upgrade changing this calculation can speed up the code.

For now, assume that the "mass" keyword still only points to one single value. Would not be hard to extend this to an array but not sure if that's what would be used? Let me know!

At the end, if np.squeeze() is used to reduce extra dimensions.

A few clarification questions.

1. Does the code need to take an array for "mass" (the mass of the orbiting body) or would it just be a single value?

2. Is this the "vectorization" you had in mind? If the single for-loop for 2-D calculations are too computationaly costly, I can probably map everything onto a 1-D array and then reshape to 2D again? That would make the code less readable, though. But it could be faster that way.

**Comment by sblunt** [comment]
Thanks again for working on this, Henry. To answer your questions:

1. Yes, we will eventually want to take in a value and some uncertainties on the system mass, so it would be good to extend that to an array. Will the code as-is just work with mass as an array (in which case we'd just update the docs), or are there some modifications to make? 
2. Yes, this is definitely the vectorization I had in mind. The computational speedup will be awesome for OFTI.

**Comment by sblunt** [comment]
One more small thing: in the docstring for `calc_orbit`, there's an incomplete line:

`mtot (np.array): total mass [Solar masses]. Note that this is`

**Comment by henry-ngo** [comment]
Just a tiny modification needed for an array input for mtot, plus finishing off that doc line. I'll update it soon!

**Comment by henry-ngo** [comment]
I think it would also be easy for me to add Jason's suggestion to eliminate for loops too, just have to convert scalar input into np.array, I think!

**Comment by sblunt** [comment]
I'm going to close this issue after you change the `mtot` code, since I think the original problem has been addressed. I'll open a new issue so y'all can talk about the best way to vectorize `kepler.py()`.

**Comment by sblunt** [comment]
@henry-ngo this issue has been addressed, right?

**Comment by henry-ngo** [comment]
yes! :)
