### ISSUE TITLE
Painfull "ValueError: Attempting to start with samples outside posterior support."

### ISSUE THREAD

**Issue by sylacour** [sblunt/orbitize#178]
Feedback from a month of working on orbitize:
1) The code is great!
2) I learned to hate the message "ValueError: Attempting to start with samples outside posterior support.". I hate it, I hate it. :p

Could it be possible to add a check on the values that are used to start the MCMC, and tell us which prior parameter is wrong? With up to 22 parameters (2 planets, RV and GAIA data), it gets very complicated to find which prior was badly initialised.

**Comment by sblunt** [comment]
Sure

**Comment by semaphoreP** [comment]
This is not helped by the fact I sent you some code with a lot of custom functionality on top of orbitize... Perhaps a function that computes the ln(prior) of each walker position and returns the bad ones that are at -inf would help?

**Comment by sylacour** [comment]
Yes, that would help. I think you wrote such a test already in the last piece of code you gave me.
But returning the bad walkers is not exactly what I would prefer. I would prefer to know which one of the prior is out of range (like: ‘m1’ or ‘ecc2’).

S.

**Comment by sblunt** [comment]
Hey Sylvestre,

Thanks for your patience! I added some documentation to the [Modifying MCMC Initial Positions tutorial](https://github.com/sblunt/orbitize/blob/main/docs/tutorials/Modifying_MCMC_initial_positions.ipynb) that will (hopefully) be useful for this problem. Since this only happens when you modify the MCMC initial positions by yourself (by default, orbitize! generates initial positions from the priors), it's difficult to incorporate an automated check within the main code base. However, I think the function I added will make this easier for your use case. Let me know!

I'm going to close this issue because I believe it has been addressed (in PR #210). If you have additional requests, feel free to open it or make a new issue.
