### ISSUE TITLE
Residuals to orbit plot

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#201]
It would be helpful to add a visualization of best-fit residuals to the orbit plot.

**Comment by sblunt** [comment]
Suggested by Andrew Howard. Thanks!

**Comment by nahimilega** [comment]
Hello @sblunt 

I am Archit Agrawal, from IIIT Delhi, India pursuing B.Tech in Computer Science and Applied Maths.

I am interested in the aim of this project of providing algorithms for orbit fitting and removing the need to have detailed prior knowledge of orbit-fitting and would be glad to get an opportunity to contribute to this library. 
This issue seems to be a good starting point in this quest. Moreover, I am fortunate to be associated with a project of the Indian Space Research Organisation(ISRO) on precise orbit determination; the experience I gained working on that project would help me to work on this issue as that project involved a visualization component too.

I am also an applicant for SURF 2021, working on this issue would help me enhance my clarity on the codebase of the orbitize.

I request you to guide me on how shall I proceed further :) 

Archit Agrawal

**Comment by sblunt** [comment]
Hey Archit,

Thanks for the message. I unfortunately don't have time to advise a new student in detail right now, but some good things to do if you're interested include:

- Reading [our paper ](https://ui.adsabs.harvard.edu/abs/2020AJ....159...89B/abstract)
- Running through some of [the tutorials ](http://orbitize.info/en/latest/tutorials.html)
- Contributing additional tests (this is a good way to get up to speed with a new package in general).

Please feel free to reach out if you have any questions!

**Comment by sblunt** [comment]
Some thoughts (by Eric)
- plot multiple residual draws on one plot (pick one to be horizontal line @ zero)
- plot residuals to median

**Comment by sblunt** [comment]
Addressed in PR #337
