### ISSUE TITLE
plot_orbits results in error when setting 'num_orbits_to_plot=1' and 'rv_time_series=True'

### ISSUE THREAD

**Issue by TirthDS** [sblunt/orbitize#243]
The error is coming from the call to 'calc_orbit' in results.py line 663. The variable 'i' in `epochs_seppa` is 1, so the indexing goes out of bounds when plotting just a single orbit. Replacing 'i' with 0 seems to fix this issue.

**Comment by sblunt** [comment]
Lea notes that i is used as an index in this part of the code several times, possibly incorrectly.

**Comment by TirthDS** [comment]
Some things found while debugging:
1. When no instruments are supplied in the input data file, default instrument names are applied to the data. The rv data will get the instrument name 'defrv'. However, `insts=[i for i in insts if 'def' not in i]` will remove this instrument from the list of instruments, so there will be no instruments. 
2. When instruments are supplied for the rv data, the rv data is correctly plotted. But, the call to calc_orbit fails due to an index issue as mentioned above, so we can't get the predicted rv trend.

**Comment by wbalmer** [comment]
I'm also getting (what I think) is the same or a related error. I have data from two RV instruments and astrometry from two instruments (one in radec and one in seppa). I supply the data with the quant1 / quant2 / quant_type format, and i can include an "instrument" column in the supplied data also for rv and imaging measurements. 

with the instrument column, attempting to plot 
epochs = my_driver.system.data_table['epoch']
myResults.plot_orbits((with object_to_plot = 1,
    num_orbits_to_plot= 1,
    start_mjd=epochs[0],
    show_colorbar = True,
    rv_time_series = True) 

I get the error "IndexError: index 0 is out of bounds for axis 0 with size 0" at line
> 671                 gam_idx=[np.where(labels==inst_gamma)[0][0] for inst_gamma in gams]


if I comment out the instrument column, and attempt to plot 
epochs = my_driver.system.data_table['epoch']
myResults.plot_orbits((with object_to_plot = 1,
    num_orbits_to_plot= 1,
    start_mjd=epochs[0],
    show_colorbar = True,
    rv_time_series = True) 

I get the error "IndexError: list index out of range" at line 
> 696                 inds[insts[i]]=np.where(data['instrument']==insts[i])[0]

Working on the current github main branch and macOS - let me know if anything more has come up with this, I'd like to fit & plot these orbits with RVs because the RV coverage is very good :)

**Comment by TirthDS** [comment]
Hello! Currently, I have not found anything else yet other than the fact that 'plot_orbits' was not actually choosing the best rv fit (taking the minimum rather than the maximum of the log probabilities) for plotting. I am not exactly sure why you're getting those errors, but they are in the same places where I was getting them.

I am making the fixes to some of the issues I pointed out earlier and will make a branch with these fixes.

**Comment by wbalmer** [comment]
Awesome - keep me updated! thanks for tackling this problem

**Comment by TirthDS** [comment]
I have pushed a new branch 'rv_plot_fix' that hopefully addresses some of the issues we had. I make sure that the rv instruments are gathered correctly before plotting and that the orbit is plotted if 'num_orbits_to_plot = 1'. Let me know whether this works for you!

**Comment by wbalmer** [comment]
Working on your branch and I think I finally got it to work! wondering how easy it would be to enable labels/different colors for astrometry points from different instruments like there are now for rv instruments?

**Comment by TirthDS** [comment]
That's great! I will take a look into that and let you know

**Comment by TirthDS** [comment]
Hey @wbalmer, apologies for the delay, but I have just pushed a change to my branch that should allow you to use different colors for astrometry points for different instruments. When making a call to `plot_orbits()`, add the following parameter: `plot_astrometry_insts=True`. Let me know how that goes for you!

**Comment by semaphoreP** [comment]
Addressed in PR #260 🎉 Thanks @TirthDS!
