### ISSUE TITLE
Incorporating Stellar RV posterior fits as priors

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#27]
Because dynamical masses are nice. Should be straightforward, but making an issue to keep track of it.

**Comment by logan-pearce** [comment]
Will also include RV for the secondary object(s) as well

**Comment by logan-pearce** [comment]
We should rewrite the entire code so that, if there are RV measurements on the primary, secondary, or both, to allow a second mass parameter for the secondary, called m2, which is determined from a mass ratio between primary and secondary.  Otherwise, if there are astrometry only, m2 will default to zero.

**Comment by logan-pearce** [comment]
We are converting the mtot to m0 - mass of the primary, changing m_planet to m1 (to be followed by m2,m3, etc when we add in more companions), and making sure that anywhere we had previously had mtot in calculations, we now change it to m0+m1 (+m2 etc).

**Comment by semaphoreP** [comment]
We decided to narrow the scope of this issue so it's just reading in RV posteriors from radvel.

**Comment by sblunt** [comment]
Addressed in PR #216! Incredible work @jorgellop and @semaphoreP, thanks so much!!
