### ISSUE TITLE
Add label for each parameter in the systems class

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#34]
This should be a field in the `System` class that lists the labels (e.g., 'a', 'e') for each parameter so we (humans) know which parameter each is. We could consider using 'a1', 'e2' to help separate multiple planets.

**Comment by henry-ngo** [comment]
Noticed that `System` currently has this description of parameter ordering for priors in its docstring

```
    Priors are initialized as a list of orbitize.priors.Prior objects,
    in the following order:

        semimajor axis b, eccentricity b, AOP b, PAN b, inclination b, EPP b, 
        [semimajor axis c, eccentricity c, etc.]
        mass, parallax

    where `b` corresponds to the first orbiting object, `c` corresponds
    to the second, etc. 
```

We should have a uniform way of numbering objects/planets, whether it's letters or numbers.  I would suggest using numbers instead of letters now to denote objects and maybe even an underscore to avoid confusion with exponents (i.e. using 'e_2' instead of 'e2' makes it more clear that it is the eccentricity of the second object, rather than the eccentricity squared)
