### ISSUE TITLE
Should system.System mass_err and plx_err be attributes?

### ISSUE THREAD

**Issue by henry-ngo** [sblunt/orbitize#43]
It looks like we can initialize system.System with a mass_err and plx_err but they aren't saved as attributes in the class definition so there's no way to access them later (e.g. I'm trying to do so when creating a results.Results object).

On a similar note, it doesn't look like system.System has a mass or plx attribute either, but instead has abs_system_mass and abs_plx? Is this intentional to have different naming? Are these attributes meant to be "public" and accessible outside of the class definition? If so, I think the different names should be mentioned in the docstring to avoid confusion!

**Comment by semaphoreP** [comment]
What's your use-case for them in `Results`? I agree with should probably save and document those fields better. We're currently using abs_plx and abs_system_mass as internal fields for when they are fixed (with no errors), rather than sampled by the MCMC, so there might be room for a more public field for system mass and parallax.

**Comment by henry-ngo** [comment]
I don't have an exact use case in mind for `Results` but I could imagine these values being important if we want to enable plotting of derived/calculated values instead of just the fitted values (e.g. plotting projected separation in au instead of arcsec, periods instead of semimajor axis etc.)

However, the main reason I asked was because Sarah's skeleton for Results defines mass_err and plx_err as optional arguments, so I was just trying to ensure we can pass it on as designed.

It sounds like we should keep abs_X as internal fields and just expose system_mass, mass_err, plx, and plx_err by making them attributes of the `System` object instead of internal values?

**Comment by semaphoreP** [comment]
Ah right. I think the two situations are: 

1) mass_err and plx_err are passed, so the sampler should be sampling them from Gaussian posteriors. In this case we shouldn't need to come back to the system class to plot them in au since that sample from the chain should have the corresponding parallax and stellar mass for that set of parameters. 
2) mass_err and plx_err are not passed. In this case, we fixed parallax and stellar mass. It's unclear to me whether we want to use abs_* in this case or whether we should keep that internal. Maybe we can just use these fields in that case instead of creating new ones.

So it seems like to me we don't need to add more fields, unless we think the current ones are harming usability.

**Comment by henry-ngo** [comment]
Ah okay. I see now that mass and parallax is part of the chain/post array so this solves the issue of having the mass and plx in the Results class. 

So if I interpret everything correctly, `Results` doesn't need to know mass_err or plx_err at all, since if we used them in Sampler, the chain would already reflect that. And if not, the chain would reflect that too. 

So, is it okay to remove the mass_err and plx_err attribute from `Results` then? Pinging @sblunt since I think the initial outline was written by Sarah and wanted to double check that I'm not removing something you have plans for!

**Comment by sblunt** [comment]
Hey all! Thanks for your patience. 

Yes, @semaphoreP's two cases are exactly what I was imaging. @henry-ngo, feel free to remove `mass_err` and `plx_err` from the `Results` class.
