### ISSUE TITLE
Disable cython features on install

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#59]
I had some issues getting cython + Windows + Python 3 to work together, but supposedly according to the Cython docs it is possible: https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

Regardless, it seems like having an option to disable cython featuers on install if the user is running into issues seems like a good idea. Basically add a flag to setup.py that disables it (E.g., `python setup.py install --disable-cython`)

**Comment by sblunt** [comment]
This is not working for `setup.py`. I will investigate.

**Comment by devincody** [comment]
what's not working?

**Comment by sblunt** [comment]
We fixed it! Documentation has been updated in commit #24f3fba7f7739ee542964717dc644829bf2a034a. Basically, if a user doesn't have `cython` AND other `orbitize` dependencies installed, the install will fail because pip tries to install dependencies without communicating not to use cython. Installing dependencies separately then installing orbitize fixes the problem (at least in one case). Thanks for responding @devincody !
