### ISSUE TITLE
How is argp defined?

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#68]
The RadVel folks had a big discussion about how argp was defined a few months ago, and I wanted to make sure I know how we're defining it. Lauren Weiss suggested I make sure I understand this.

 See Figure 1 of BJ's 2017 RadVel paper. Are we defining argp the same way they do, with a 180deg offset, or some other way?

**Comment by semaphoreP** [comment]
I believe we define it as angle from ascending node to the periastron of the **planet's** orbit, so we are 180 degrees off from RadVel, which does it to periastron of the star's orbit.

**Comment by rjderosa** [comment]
I think RV folks define it differently from those doing visual orbits, which sort of makes sense because with RV you are tracking the orbit of the primary. Coming from the direct imaging side, I'd argue we keep things the way they are right now.

**Comment by henry-ngo** [comment]
argp is always defined as the angle from the ascending node to the periastron of the object you're tracking. I agree with Rob that for us, it makes sense to do it for the periastron of the companion's orbit since we're fitting the companion's orbit, while the RadVel folks care about the primary so they do that. Solar system folks also define argp the same way we do, so it's the RV folks that are the anomaly, in my opinion (but for good reason!)

So I also support keeping things the way they are now too. If someone unfamiliar with our package but familiar with orbit fitting in general came across our package, they would likely expect argp to be defined the way they are now.

**Comment by sblunt** [comment]
That makes a ton of sense. Thanks all for the very clear explanations!
